# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
name: Feature Request
description: I would like to propose a new feature or enhance an existing one.
labels: ["feature"]
body:
  - type: checkboxes
    attributes:
      label: Before opening a new issue, take a moment to validate its a unique (new) issue.
      description: 'If you find a similar issue, please put your attention there.'
      options:
        - label: This issue has not been previously reported.
          required: true

  - type: markdown
    attributes:
      value: ---

  - type: textarea
    id: desc
    attributes:
      label: Feature Description
      description: Please provide a detailed description of your proposed feature.
      render: sh
    validations:
      required: true
